apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps  
  namespace: aks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
        - name: myapps
          image: naga1919.azurecr.io/naga1919:1.0.0
          ports:
            - containerPort: 80
    imagePullSecret:
                    -name: acr-alex
