apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: naga111
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match **>
      @type stdout
    </match>