apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nag-image-hpa
  namespace: sai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nag-image
  minReplicas: 1
  maxReplicas: 11
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50