apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nag-image
spec:
  podSelector:
    matchLabels:
      app: nag-image
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: backend