apiVersion: v1
kind: Service
metadata:
  name: docker21-dotnet6
  namespace: naga111
spec:
  selector:
    app: docker21-dotnet6
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
